### ISSUE TITLE
non-ascii passwords lead to exception

### ISSUE THREAD

**Issue by robinro** [jamesls/python-keepassx#3]
I use a db with a password containing non-ascii characters. After entering the password I get the exception listed below. It should be possible to have utf-8 input.
Maybe it's related with this: https://bugs.python.org/issue21169
To test, you can use one of öäüß (common german non-ascii characters)

  File "/usr/local/bin/kp", line 4, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/keepassx/main.py", line 171, in main
    args.run(args)
  File "/usr/local/lib/python2.7/dist-packages/keepassx/main.py", line 60, in do_list
    db = create_db(args)
  File "/usr/local/lib/python2.7/dist-packages/keepassx/main.py", line 55, in create_db
    key_file_contents=key_file_contents)
  File "/usr/local/lib/python2.7/dist-packages/keepassx/db.py", line 118, in __init__
    self._calculate_key(password.encode('utf-8'), key_file_contents,
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)

**Comment by jamesls** [comment]
I agree this should be fixed.

One of the things I'm noticing (after fixing the bug in your traceback) is that it's not actually clear exactly how keepassx encocdes passwords containing non-ascii chars.  Will need to dig a bit deeper to figure how this works.

**Comment by jamesls** [comment]
Ok, have a partial fix for this, but I noticed something interesting in the source of the keepassx source code in Kdb3Database.cpp where it encodes the master key:

```
bool Kdb3Database::setPasswordKey(const QString& Password){
	QTextCodec* codec=QTextCodec::codecForName("Windows-1252");
	QByteArray Password_CP1252 = codec->fromUnicode(Password);
	RawMasterKey_CP1252.unlock();
	SHA256::hashBuffer(Password_CP1252.data(),*RawMasterKey_CP1252,Password_CP1252.size());
	RawMasterKey_CP1252.lock();
	RawMasterKey.copyData(RawMasterKey_CP1252);

```

What's interesting is that Windows-1252 can't encode all unicode code points so I still need to track down what happens in this scenario.  The QT docs don't really say much about what happens when it encounters unicode it can't encode (http://doc.qt.io/qt-4.8/qtextcodec.html#fromUnicode).

**Comment by jamesls** [comment]
This is now fixed.  One interesting thing that I didn't realize is that the above code snippet will replace any chars it can't encode with `?`, which means that passwords such as "password✒", "password✓", and "password?" are all equivalent.  However, as long as you can encode your password with cp1252 (which the chars you show in your original post can be encoded with cp1252) then you won't run into this issue.

Thanks for reporting.

**Comment by robinro** [comment]
Thanks a lot for the fix. I'll try it out and reopen if I still find something not working.
