### ISSUE TITLE
Support for getting password from stdin

### ISSUE THREAD

**Issue by chmduquesne** [jamesls/python-keepassx#5]
Hi,

I like python-keepassx, but I would like to script it from a gui with yad or zenity. Ideally, I would get the password from a gui or from gnome-keyring. Is it possible to add an option such as

    --stdin

in order to read the password from stdin (and not with the module getpass)?

I would use it like this:

    password=$(gnome-keyring-query get keepassx | kp --stdin get github)

**Comment by jamesls** [comment]
I think that seems reasonable, marking as a feature request.

**Comment by chmduquesne** [comment]
Thank you for implementing this!

FYI I made a package for archlinux

https://aur.archlinux.org/packages/python-keepassx/
https://aur4.archlinux.org/packages/python-keepassx/
