### ISSUE TITLE
Simple CLI, but not API

### ISSUE THREAD

**Issue by zoresvit** [jamesls/python-keepassx#8]
Hi, so the project seems great, but I'd argue the "simple API" statement as  the actual Python API seems to be undocumented. At least I couldn't find anything useful in the [docs](http://keepassx.readthedocs.org/en/latest/index.html). There is only information about CLI, but not Python bindings.

If I'm missing it, could you point me into Python API documentation and examples? If not, could you describe how I should open the DB file to search for entries?

Thanks!

**Comment by barsanuphe** [comment]
I couldn't find actual API documentation either, but the code is well documented.
Check keepassx/db.py for the API, and keepassx/main.py for an example.

A quick very simple example:

    from keepassx.db import Database
    from pathlib import Path

    db_file = Path("secret.kdb")
    db = Database(db_file.open("rb").read(), password=b"password")
    entry = db.find_by_title("test1")
    print("%s.%s: %s" % (entry.group.group_name,
                         entry.title,
                         entry.password))

**Comment by zoresvit** [comment]
Good old "who needs documentation, just look in the code" :)

But thanks, it works :+1:
